name: velocity
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0+1

environment:
  sdk: ^3.12.2

dependencies:
  font_awesome_flutter: 11.0.0
  flutter:
    sdk: flutter
  dotted_border: ^2.1.0
  file_picker: 12.0.0-beta.7 #10.3.8
  lucide_icons_flutter: ^3.0.5
  path_provider: ^2.1.6
  image: ^4.3.0
  open_filex: ^4.7.0
  gal: ^2.3.2    
  share_plus: ^13.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  integration_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/fonts/

  fonts:
    - family: InterVariable
      fonts:
        - asset: assets\fonts\Inter\Inter-VariableFont_opsz,wght.ttf
    - family: JetBrainsMonoVariable
      fonts:
        - asset: assets\fonts\JetBrainsMono\JetBrainsMono[wght].ttf